version: '3.9'
services:
  database:
    container_name: kite_database
    image: postgres:13.1
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - kite-db:/var/lib/postgresql
    ports:
      - '5432:5432'

volumes:
  kite-db:
