name: telegram message on Pull Request
on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main
jobs:
  build:
    name: Notify PR
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on PR
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            **${{ github.actor }} created a PR:**
            ${{ github.event.pull_request.title }}

            [#${{ github.event.pull_request.number }}](https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }})


