name: telegram message on Pull Request
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Notify PR
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on PR
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created PR.
